# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CTMediatorPratice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'Masonry', :git => 'https://github.com/SnapKit/Masonry.git', :inhibit_warnings => true

#  pod "CTProjectCategory", :git => 'https://github.com/GItHubNanmu77/CTProjectCategory.git',:tag=>'1.0.4', :inhibit_warnings => true
  pod "FirstSection", :git => 'https://github.com/GItHubNanmu77/CTFirstSection.git', :tag =>'1.0.1',:inhibit_warnings => true
  # Pods for CTMediatorPratice

  target 'CTMediatorPraticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CTMediatorPraticeUITests' do
    # Pods for testing
  end

end
